### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by casimirlaine** [ereborinkorppi/tiralabra#1]
The project, overall, has a great structure to it and it is very easy to install and test with poetry.
I would, however, split the main function of index.py into separate functions to make the code a bit cleaner.

The program is implemented in an in-program way rather than a command liner interface way. That is purely a preference, but using the CLI approach would allow for more flexibility when scripting and automating the compression of multiple files. There is also a tedious restriction on only compressing .txt files and decompressing .bin files. What if a user wants to compress images, for example?

The 78 variation of the Lemple-Ziv algorithm is implemented in a rather clean and clear way. The code is concise and easily modifiable if needed. In the current implementation, the encoding returns a bytearray-object and decoding returns a string object. I would make it so that both methods return an object of the same type and handle conversions elsewhere. In addition, to support for any binary encoded data it is false to assume that it can be represented by a string object. And to add that support the data has to be treated everywhere as bytes.

The Huffman algorithm is also implemented in a good way, although there is still room for code quality improvement.
For example here: 
right = self.nodes[0]
left = self.nodes[1]

left.code = 0
right.code = 1

new_node = Node(left.prob+right.prob, left.symbol+right.symbol, left, right)
self.nodes.remove(left)
self.nodes.remove(right)

I would just pop the left and right node with list.pop().
In the split_tree_coding method's for-each loop, indexing is also used which is confusing.

There are multiple conversions between str, bytes, and int objects. I wonder whether this is really necessary since it adds a bit extra overhead. In both algorithms, I would add type hints everywhere to make it very clear when we are dealing with str, bytes, int, or bytearray objects. It is tedious to check the types with a debugger before making any edits.

The division of steps of the algorithm into methods is done in an excellent way!

To further optimize the algorithms the data could be dealt with on a bit-level using the bitarray module (https://pypi.org/project/bitarray/).

Great work!

The project was cloned on 20.8.2022 at 21.30.

**Comment by ereborinkorppi** [comment]
Thank you for the really valuable feedback. Some of your comments I was already aware of like, splitting the index.py (should do that I have enough time) and the fact that my HuffmanAlgo cloud be a lot tidier, although I guess it would require too much time to make it as it should be. I could do few spot on fixes like the one you pointed out there. 

You are absolutely right that there's too many conversions especially in Huffman, but also this is probably something that I don't find time to fix. 

There's basically one thing I like to disagree with your feedback: that is my restriction to purely .txt compression and .bin decompression. I am only comparing performance of these two algorithms in text file compression and therefore I have made these restrictions. I have not tested it with other types and I will not test it that way. This is why I like be sure that my program actually works rather than allowing flexibility with other types I have not tested.

One more time thank you for the feedback, useful stuff!
